ALL: my-cat my-grep my-zip my-unzip

my-cat: my-cat.c
	gcc -o my-cat my-cat.c -Wall -Werror

my-grep: my-grep.c
	gcc -o my-grep my-grep.c -Wall -Werror

my-zip: my-zip.c
	gcc -o my-zip my-zip.c -Wall -Werror

my-unzip: my-unzip.c
	gcc -o my-unzip my-unzip.c -Wall -Werror
